services:
  - type: web
    name: credential-verification-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -k uvicorn.workers.UvicornWorker app.main:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
      - key: DATABASE_URL
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
